version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9280:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch   

  app:
    build: .
    networks:
      - esnet
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge 
